--=======================TESTING VIEWS===================================================

SELECT * FROM GET_ALL_STUDENTS 
SELECT * FROM GET_ALL_STUDENTS_COUNTRY
SELECT * FROM GET_CREDITS_BY_COURSE
SELECT * FROM GET_STUDENTS_BY_COURSE
SELECT * FROM GET_COUNT_AGE
SELECT * FROM GET_INSTRUCTOR_NO_PHOTO
SELECT * FROM GET_STUDENTS_BY_AGE_RANGE(18,20)
SELECT * FROM GET_COURSES_BY_CREDIT_RANGE(15,20)
SELECT * FROM GET_STUDENTS_ENROLMENT_DATE('2020-01-01','2020-12-31')
SELECT * FROM GET_PHONE_NUMBER_LIKE_322
SELECT * FROM GET_PHONE_NUMBER_LIKE(322)
SELECT * FROM GET_COURSE_LIKE_DATA
SELECT * FROM GET_TOTAL_STUDENTS_IN_SYSTEM
SELECT * FROM GET_AVERAGE_AGE_OF_STUDENTS
SELECT * FROM GET_COURSE_AVERAGE_AGE
SELECT * FROM GET_STUDENTS_OF_18
SELECT * FROM GET_PROFIT_BY_COURSE
SELECT * FROM GET_OLDEST_STUDENT
SELECT * FROM GET_NEW_ENROLMENTS('2020-01-01', '2020-12-31')
SELECT * FROM GET_COUNTRIES_WITH_NO_STUDENT
SELECT * FROM GET_COURSES_WITH_NO_ENROLMENTS









